server:
  port: 8084

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/oauth2/jwks

srm:
  api:
    cors:
      allowed-origins:
        - http://localhost:4200
