spring:
  application:
    name: srm
  datasource:
    main:
      url: jdbc:sqlserver://172.20.0.238:1433;databaseName=AdvantechSRM;encrypt=false
      username: 
      password: 
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect