server:
  port: 8081
  servlet:
    session:
      cookie:
        name: SRM-AUTH-SESSION

spring:
  datasource:
    url: jdbc:h2:mem:srm-auth;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

srm:
  auth:
    cors:
      allowed-origins:
        - http://localhost:4200
    oauth2:
      client-id: srm-frontend
      redirect-uris:
        - http://localhost:4200/auth/callback
      scopes:
        - openid
        - profile
      access-token-ttl-minutes: 15
      refresh-token-ttl-hours: 24
      issuer: http://localhost:8081
    soap:
      enabled: false
      mock-users:
        - user-id: adv-employee
          email: employee@advantech.com
          password: pass1234
          display-name: Advantech Employee
          roles:
            - ROLE_INTERNAL
          permissions:
            - vendors.read
