server:
  port: 9000
  servlet:
    session:
      cookie:
        name: SRM-AUTH-SESSION
        http-only: true
        same-site: lax
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:h2:mem:srm-auth;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    com.advantech.srm.auth.config: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server.authorization: TRACE
    org.springframework.security.oauth2.server.authorization.web: TRACE

srm:
  auth:
    cors:
      allowed-origins:
        - http://localhost:4200
        - http://127.0.0.1:4200
    oauth2:
      client-id: app-bff
      client-secret: bff-secret
      redirect-uris:
        - http://localhost:8081/oauth/callback
        - http://localhost:4200/oauth/callback
        - http://127.0.0.1:4200/oauth/callback
        - http://127.0.0.1:8081/oauth/callback
      scopes:
        - openid
        - profile
      access-token-ttl-minutes: 15
      refresh-token-ttl-hours: 24
      issuer: http://localhost:9000
    soap:
      enabled: false
      mock-users:
        - user-id: adv-employee
          email: employee@advantech.com
          password: pass1234
          display-name: Advantech Employee
          roles:
            - ROLE_INTERNAL
          permissions:
            - vendors.read

