services:
  srm-api:
    build:
      context: ../../back-end/srm
      dockerfile: ./srm-api/Dockerfile
    volumes:
      - gradle_cache:/home/gradle/.gradle
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  gradle_cache:

networks:
  backend:
